language: go

go:
  - 1.13.x

env:
  - GO111MODULE=on

script:
  - go test -v chatMsg/..
  - go test -v Keeper/..
  - go test -v Master/..
  - go test -v util/..
  - make server
  - make keeper