// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0
// 	protoc        v3.11.4
// source: proto/MasterServerApi/MasterServerApi.proto

package MasterServerApi

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type KeeperAddReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	KeeperUrl string `protobuf:"bytes,3,opt,name=keeper_url,json=keeperUrl,proto3" json:"keeper_url,omitempty"`
}

func (x *KeeperAddReq) Reset() {
	*x = KeeperAddReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_MasterServerApi_MasterServerApi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeeperAddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeeperAddReq) ProtoMessage() {}

func (x *KeeperAddReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_MasterServerApi_MasterServerApi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeeperAddReq.ProtoReflect.Descriptor instead.
func (*KeeperAddReq) Descriptor() ([]byte, []int) {
	return file_proto_MasterServerApi_MasterServerApi_proto_rawDescGZIP(), []int{0}
}

func (x *KeeperAddReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *KeeperAddReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KeeperAddReq) GetKeeperUrl() string {
	if x != nil {
		return x.KeeperUrl
	}
	return ""
}

type KeeperAddResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status    string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *KeeperAddResp) Reset() {
	*x = KeeperAddResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_MasterServerApi_MasterServerApi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeeperAddResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeeperAddResp) ProtoMessage() {}

func (x *KeeperAddResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_MasterServerApi_MasterServerApi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeeperAddResp.ProtoReflect.Descriptor instead.
func (*KeeperAddResp) Descriptor() ([]byte, []int) {
	return file_proto_MasterServerApi_MasterServerApi_proto_rawDescGZIP(), []int{1}
}

func (x *KeeperAddResp) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *KeeperAddResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type KeeperSyncReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string   `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PackMsg   [][]byte `protobuf:"bytes,2,rep,name=pack_msg,json=packMsg,proto3" json:"pack_msg,omitempty"`
}

func (x *KeeperSyncReq) Reset() {
	*x = KeeperSyncReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_MasterServerApi_MasterServerApi_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeeperSyncReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeeperSyncReq) ProtoMessage() {}

func (x *KeeperSyncReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_MasterServerApi_MasterServerApi_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeeperSyncReq.ProtoReflect.Descriptor instead.
func (*KeeperSyncReq) Descriptor() ([]byte, []int) {
	return file_proto_MasterServerApi_MasterServerApi_proto_rawDescGZIP(), []int{2}
}

func (x *KeeperSyncReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *KeeperSyncReq) GetPackMsg() [][]byte {
	if x != nil {
		return x.PackMsg
	}
	return nil
}

type KeeperSyncResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string   `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PackMsg   [][]byte `protobuf:"bytes,2,rep,name=pack_msg,json=packMsg,proto3" json:"pack_msg,omitempty"`
}

func (x *KeeperSyncResp) Reset() {
	*x = KeeperSyncResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_MasterServerApi_MasterServerApi_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeeperSyncResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeeperSyncResp) ProtoMessage() {}

func (x *KeeperSyncResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_MasterServerApi_MasterServerApi_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeeperSyncResp.ProtoReflect.Descriptor instead.
func (*KeeperSyncResp) Descriptor() ([]byte, []int) {
	return file_proto_MasterServerApi_MasterServerApi_proto_rawDescGZIP(), []int{3}
}

func (x *KeeperSyncResp) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *KeeperSyncResp) GetPackMsg() [][]byte {
	if x != nil {
		return x.PackMsg
	}
	return nil
}

var File_proto_MasterServerApi_MasterServerApi_proto protoreflect.FileDescriptor

var file_proto_MasterServerApi_MasterServerApi_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x41, 0x70, 0x69, 0x2f, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x41, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x41, 0x70, 0x69, 0x22, 0x60, 0x0a, 0x0c, 0x4b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x41, 0x64,
	0x64, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6b, 0x65, 0x65, 0x70, 0x65,
	0x72, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6b, 0x65, 0x65,
	0x70, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x22, 0x46, 0x0a, 0x0d, 0x4b, 0x65, 0x65, 0x70, 0x65, 0x72,
	0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x49,
	0x0a, 0x0d, 0x4b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x71, 0x12,
	0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x19,
	0x0a, 0x08, 0x70, 0x61, 0x63, 0x6b, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c,
	0x52, 0x07, 0x70, 0x61, 0x63, 0x6b, 0x4d, 0x73, 0x67, 0x22, 0x4a, 0x0a, 0x0e, 0x4b, 0x65, 0x65,
	0x70, 0x65, 0x72, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x61,
	0x63, 0x6b, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61,
	0x63, 0x6b, 0x4d, 0x73, 0x67, 0x32, 0xc9, 0x01, 0x0a, 0x10, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x70, 0x69, 0x12, 0x58, 0x0a, 0x09, 0x4b, 0x65,
	0x65, 0x70, 0x65, 0x72, 0x41, 0x64, 0x64, 0x12, 0x23, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x70, 0x69, 0x2e,
	0x4b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x24, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x41, 0x70, 0x69, 0x2e, 0x4b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x41, 0x64, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x22, 0x00, 0x12, 0x5b, 0x0a, 0x0a, 0x4b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x53, 0x79,
	0x6e, 0x63, 0x12, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x61, 0x73, 0x74, 0x65,
	0x72, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x70, 0x69, 0x2e, 0x4b, 0x65, 0x65, 0x70, 0x65,
	0x72, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x71, 0x1a, 0x25, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x70, 0x69,
	0x2e, 0x4b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x00, 0x42, 0x17, 0x5a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x4d, 0x61, 0x73, 0x74, 0x65,
	0x72, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_MasterServerApi_MasterServerApi_proto_rawDescOnce sync.Once
	file_proto_MasterServerApi_MasterServerApi_proto_rawDescData = file_proto_MasterServerApi_MasterServerApi_proto_rawDesc
)

func file_proto_MasterServerApi_MasterServerApi_proto_rawDescGZIP() []byte {
	file_proto_MasterServerApi_MasterServerApi_proto_rawDescOnce.Do(func() {
		file_proto_MasterServerApi_MasterServerApi_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_MasterServerApi_MasterServerApi_proto_rawDescData)
	})
	return file_proto_MasterServerApi_MasterServerApi_proto_rawDescData
}

var file_proto_MasterServerApi_MasterServerApi_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_MasterServerApi_MasterServerApi_proto_goTypes = []interface{}{
	(*KeeperAddReq)(nil),   // 0: proto.MasterServerApi.KeeperAddReq
	(*KeeperAddResp)(nil),  // 1: proto.MasterServerApi.KeeperAddResp
	(*KeeperSyncReq)(nil),  // 2: proto.MasterServerApi.KeeperSyncReq
	(*KeeperSyncResp)(nil), // 3: proto.MasterServerApi.KeeperSyncResp
}
var file_proto_MasterServerApi_MasterServerApi_proto_depIdxs = []int32{
	0, // 0: proto.MasterServerApi.MasterServiceApi.KeeperAdd:input_type -> proto.MasterServerApi.KeeperAddReq
	2, // 1: proto.MasterServerApi.MasterServiceApi.KeeperSync:input_type -> proto.MasterServerApi.KeeperSyncReq
	1, // 2: proto.MasterServerApi.MasterServiceApi.KeeperAdd:output_type -> proto.MasterServerApi.KeeperAddResp
	3, // 3: proto.MasterServerApi.MasterServiceApi.KeeperSync:output_type -> proto.MasterServerApi.KeeperSyncResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_MasterServerApi_MasterServerApi_proto_init() }
func file_proto_MasterServerApi_MasterServerApi_proto_init() {
	if File_proto_MasterServerApi_MasterServerApi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_MasterServerApi_MasterServerApi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeeperAddReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_MasterServerApi_MasterServerApi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeeperAddResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_MasterServerApi_MasterServerApi_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeeperSyncReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_MasterServerApi_MasterServerApi_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeeperSyncResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_MasterServerApi_MasterServerApi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_MasterServerApi_MasterServerApi_proto_goTypes,
		DependencyIndexes: file_proto_MasterServerApi_MasterServerApi_proto_depIdxs,
		MessageInfos:      file_proto_MasterServerApi_MasterServerApi_proto_msgTypes,
	}.Build()
	File_proto_MasterServerApi_MasterServerApi_proto = out.File
	file_proto_MasterServerApi_MasterServerApi_proto_rawDesc = nil
	file_proto_MasterServerApi_MasterServerApi_proto_goTypes = nil
	file_proto_MasterServerApi_MasterServerApi_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MasterServiceApiClient is the client API for MasterServiceApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MasterServiceApiClient interface {
	KeeperAdd(ctx context.Context, in *KeeperAddReq, opts ...grpc.CallOption) (*KeeperAddResp, error)
	KeeperSync(ctx context.Context, in *KeeperSyncReq, opts ...grpc.CallOption) (*KeeperSyncResp, error)
}

type masterServiceApiClient struct {
	cc grpc.ClientConnInterface
}

func NewMasterServiceApiClient(cc grpc.ClientConnInterface) MasterServiceApiClient {
	return &masterServiceApiClient{cc}
}

func (c *masterServiceApiClient) KeeperAdd(ctx context.Context, in *KeeperAddReq, opts ...grpc.CallOption) (*KeeperAddResp, error) {
	out := new(KeeperAddResp)
	err := c.cc.Invoke(ctx, "/proto.MasterServerApi.MasterServiceApi/KeeperAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterServiceApiClient) KeeperSync(ctx context.Context, in *KeeperSyncReq, opts ...grpc.CallOption) (*KeeperSyncResp, error) {
	out := new(KeeperSyncResp)
	err := c.cc.Invoke(ctx, "/proto.MasterServerApi.MasterServiceApi/KeeperSync", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MasterServiceApiServer is the server API for MasterServiceApi service.
type MasterServiceApiServer interface {
	KeeperAdd(context.Context, *KeeperAddReq) (*KeeperAddResp, error)
	KeeperSync(context.Context, *KeeperSyncReq) (*KeeperSyncResp, error)
}

// UnimplementedMasterServiceApiServer can be embedded to have forward compatible implementations.
type UnimplementedMasterServiceApiServer struct {
}

func (*UnimplementedMasterServiceApiServer) KeeperAdd(context.Context, *KeeperAddReq) (*KeeperAddResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KeeperAdd not implemented")
}
func (*UnimplementedMasterServiceApiServer) KeeperSync(context.Context, *KeeperSyncReq) (*KeeperSyncResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KeeperSync not implemented")
}

func RegisterMasterServiceApiServer(s *grpc.Server, srv MasterServiceApiServer) {
	s.RegisterService(&_MasterServiceApi_serviceDesc, srv)
}

func _MasterServiceApi_KeeperAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeeperAddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServiceApiServer).KeeperAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MasterServerApi.MasterServiceApi/KeeperAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServiceApiServer).KeeperAdd(ctx, req.(*KeeperAddReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterServiceApi_KeeperSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeeperSyncReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServiceApiServer).KeeperSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MasterServerApi.MasterServiceApi/KeeperSync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServiceApiServer).KeeperSync(ctx, req.(*KeeperSyncReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _MasterServiceApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MasterServerApi.MasterServiceApi",
	HandlerType: (*MasterServiceApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "KeeperAdd",
			Handler:    _MasterServiceApi_KeeperAdd_Handler,
		},
		{
			MethodName: "KeeperSync",
			Handler:    _MasterServiceApi_KeeperSync_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/MasterServerApi/MasterServerApi.proto",
}
