// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0
// 	protoc        v3.11.4
// source: RemoteCall.proto

package proto

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CallRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FuncName   string   `protobuf:"bytes,3,opt,name=funcName,proto3" json:"funcName,omitempty"`
	ParamsList []string `protobuf:"bytes,1,rep,name=paramsList,proto3" json:"paramsList,omitempty"`
	TypeList   []string `protobuf:"bytes,2,rep,name=TypeList,proto3" json:"TypeList,omitempty"`
}

func (x *CallRequest) Reset() {
	*x = CallRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RemoteCall_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallRequest) ProtoMessage() {}

func (x *CallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_RemoteCall_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallRequest.ProtoReflect.Descriptor instead.
func (*CallRequest) Descriptor() ([]byte, []int) {
	return file_RemoteCall_proto_rawDescGZIP(), []int{0}
}

func (x *CallRequest) GetFuncName() string {
	if x != nil {
		return x.FuncName
	}
	return ""
}

func (x *CallRequest) GetParamsList() []string {
	if x != nil {
		return x.ParamsList
	}
	return nil
}

func (x *CallRequest) GetTypeList() []string {
	if x != nil {
		return x.TypeList
	}
	return nil
}

type CallReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status     string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ParamsList []string `protobuf:"bytes,1,rep,name=paramsList,proto3" json:"paramsList,omitempty"`
	TypeList   []string `protobuf:"bytes,2,rep,name=TypeList,proto3" json:"TypeList,omitempty"`
}

func (x *CallReply) Reset() {
	*x = CallReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RemoteCall_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallReply) ProtoMessage() {}

func (x *CallReply) ProtoReflect() protoreflect.Message {
	mi := &file_RemoteCall_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallReply.ProtoReflect.Descriptor instead.
func (*CallReply) Descriptor() ([]byte, []int) {
	return file_RemoteCall_proto_rawDescGZIP(), []int{1}
}

func (x *CallReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CallReply) GetParamsList() []string {
	if x != nil {
		return x.ParamsList
	}
	return nil
}

func (x *CallReply) GetTypeList() []string {
	if x != nil {
		return x.TypeList
	}
	return nil
}

type RemoteEmpty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemoteEmpty) Reset() {
	*x = RemoteEmpty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RemoteCall_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoteEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteEmpty) ProtoMessage() {}

func (x *RemoteEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_RemoteCall_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteEmpty.ProtoReflect.Descriptor instead.
func (*RemoteEmpty) Descriptor() ([]byte, []int) {
	return file_RemoteCall_proto_rawDescGZIP(), []int{2}
}

type RemoteConfirmReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *RemoteConfirmReply) Reset() {
	*x = RemoteConfirmReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_RemoteCall_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoteConfirmReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteConfirmReply) ProtoMessage() {}

func (x *RemoteConfirmReply) ProtoReflect() protoreflect.Message {
	mi := &file_RemoteCall_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteConfirmReply.ProtoReflect.Descriptor instead.
func (*RemoteConfirmReply) Descriptor() ([]byte, []int) {
	return file_RemoteCall_proto_rawDescGZIP(), []int{3}
}

func (x *RemoteConfirmReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_RemoteCall_proto protoreflect.FileDescriptor

var file_RemoteCall_proto_rawDesc = []byte{
	0x0a, 0x10, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x43, 0x61, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x65, 0x0a, 0x0b, 0x43, 0x61, 0x6c,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x75, 0x6e, 0x63,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x75, 0x6e, 0x63,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x4c, 0x69,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x79, 0x70, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x54, 0x79, 0x70, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x22, 0x5f, 0x0a, 0x09, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x4c,
	0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x61, 0x72, 0x61, 0x6d,
	0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x79, 0x70, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x54, 0x79, 0x70, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x22, 0x0d, 0x0a, 0x0b, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x22, 0x2c, 0x0a, 0x12, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72,
	0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x78,
	0x0a, 0x0a, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x2e, 0x0a, 0x04,
	0x43, 0x61, 0x6c, 0x6c, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x61, 0x6c,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x07,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x12, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x19, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72,
	0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_RemoteCall_proto_rawDescOnce sync.Once
	file_RemoteCall_proto_rawDescData = file_RemoteCall_proto_rawDesc
)

func file_RemoteCall_proto_rawDescGZIP() []byte {
	file_RemoteCall_proto_rawDescOnce.Do(func() {
		file_RemoteCall_proto_rawDescData = protoimpl.X.CompressGZIP(file_RemoteCall_proto_rawDescData)
	})
	return file_RemoteCall_proto_rawDescData
}

var file_RemoteCall_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_RemoteCall_proto_goTypes = []interface{}{
	(*CallRequest)(nil),        // 0: proto.CallRequest
	(*CallReply)(nil),          // 1: proto.CallReply
	(*RemoteEmpty)(nil),        // 2: proto.RemoteEmpty
	(*RemoteConfirmReply)(nil), // 3: proto.RemoteConfirmReply
}
var file_RemoteCall_proto_depIdxs = []int32{
	0, // 0: proto.RemoteCall.Call:input_type -> proto.CallRequest
	2, // 1: proto.RemoteCall.Confirm:input_type -> proto.RemoteEmpty
	1, // 2: proto.RemoteCall.Call:output_type -> proto.CallReply
	3, // 3: proto.RemoteCall.Confirm:output_type -> proto.RemoteConfirmReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_RemoteCall_proto_init() }
func file_RemoteCall_proto_init() {
	if File_RemoteCall_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_RemoteCall_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RemoteCall_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RemoteCall_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoteEmpty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_RemoteCall_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoteConfirmReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_RemoteCall_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_RemoteCall_proto_goTypes,
		DependencyIndexes: file_RemoteCall_proto_depIdxs,
		MessageInfos:      file_RemoteCall_proto_msgTypes,
	}.Build()
	File_RemoteCall_proto = out.File
	file_RemoteCall_proto_rawDesc = nil
	file_RemoteCall_proto_goTypes = nil
	file_RemoteCall_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RemoteCallClient is the client API for RemoteCall service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RemoteCallClient interface {
	Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallReply, error)
	Confirm(ctx context.Context, in *RemoteEmpty, opts ...grpc.CallOption) (*RemoteConfirmReply, error)
}

type remoteCallClient struct {
	cc grpc.ClientConnInterface
}

func NewRemoteCallClient(cc grpc.ClientConnInterface) RemoteCallClient {
	return &remoteCallClient{cc}
}

func (c *remoteCallClient) Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallReply, error) {
	out := new(CallReply)
	err := c.cc.Invoke(ctx, "/proto.RemoteCall/Call", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteCallClient) Confirm(ctx context.Context, in *RemoteEmpty, opts ...grpc.CallOption) (*RemoteConfirmReply, error) {
	out := new(RemoteConfirmReply)
	err := c.cc.Invoke(ctx, "/proto.RemoteCall/Confirm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RemoteCallServer is the server API for RemoteCall service.
type RemoteCallServer interface {
	Call(context.Context, *CallRequest) (*CallReply, error)
	Confirm(context.Context, *RemoteEmpty) (*RemoteConfirmReply, error)
}

// UnimplementedRemoteCallServer can be embedded to have forward compatible implementations.
type UnimplementedRemoteCallServer struct {
}

func (*UnimplementedRemoteCallServer) Call(context.Context, *CallRequest) (*CallReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Call not implemented")
}
func (*UnimplementedRemoteCallServer) Confirm(context.Context, *RemoteEmpty) (*RemoteConfirmReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Confirm not implemented")
}

func RegisterRemoteCallServer(s *grpc.Server, srv RemoteCallServer) {
	s.RegisterService(&_RemoteCall_serviceDesc, srv)
}

func _RemoteCall_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteCallServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RemoteCall/Call",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteCallServer).Call(ctx, req.(*CallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoteCall_Confirm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoteEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteCallServer).Confirm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RemoteCall/Confirm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteCallServer).Confirm(ctx, req.(*RemoteEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

var _RemoteCall_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.RemoteCall",
	HandlerType: (*RemoteCallServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _RemoteCall_Call_Handler,
		},
		{
			MethodName: "Confirm",
			Handler:    _RemoteCall_Confirm_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "RemoteCall.proto",
}
